### ISSUE TITLE
GPS data zero after wake-up

### ISSUE THREAD

**Issue by jeroenkl** [beegee-tokyo/RAK4631-Kit-2-RAK1910-RAK1904-RAK1906#1]
Hi bengee,

I've got issue's to get a GPS fix (outside, clear view). 
Looks like there is not enough time to get a fix after a wake-up. Is it easy possible to keep the GPS sensor awake? 
I could not find this setting, could you please help to adjust this?

BR, Jeroen

**Comment by beegee-tokyo** [comment]
Depending on the location it can take up to 60 seconds after cold start to find a fix. During tests, I set the `send_repeat_time` to 120 seconds.
What `send_repeat_time` did you set? The search time is calculated based on this value:

```c++
	//  If no automatic sending, set search time to 90 seconds
	if (g_lorawan_settings.send_repeat_time == 0)
	{
		check_limit = 90000;
	}
	//  If send_repeat_time is less than 90 seconds, search for 1/2 of that time
	//  Can lead to no location fix at all
	else if (g_lorawan_settings.send_repeat_time <= 90000)
	{
		check_limit = g_lorawan_settings.send_repeat_time / 2;
	}
	else
	{
		//  If send_repeat_time more than 90 seconds, search for 90 seconds
		// If send_repeat_time is 90 seconds, the device will never sleep
		check_limit = 90000;
	}
```

If you want to keep the GPS powered up all the time, there are two places in the code you need to change.

In **`gnss.cpp`**:
In **`poll_gnss()`** you need to remove lines 72-73:
```c++
	digitalWrite(WB_IO2, HIGH);
	// Give the module some time to power up
	delay(500);
```
and lines 219 to 221:
```c++
	// Power down the module
	pinMode(WB_IO2, OUTPUT);
	digitalWrite(WB_IO2, LOW);
```
But your current consumption will go up. There is unfortunately no sleep mode for the RAK1910 available.

**Comment by jeroenkl** [comment]
Hi Bernd,

My send_repeat_time was set to 60 sec, I changed it now to 120 and will test again before I change the GPS power-up to always ON.

Thanks!
Jeroen
